General:
  rag_space: "my_electronics_kb" # 你的知识库名称，将作为顶级文件夹名

PDF processing:
  OCR: false
  Page save: true  # 设置为 true 来保存分页图片，false 则不保存
  Page dpi: 200    # 设置保存图片的分辨率 (DPI)

Chunking:
  strategy: semantic  # 分块策略。可选值: 'fixed' 或 'semantic'

  # 'fixed' 策略的配置
  fixed_size: 1000
  fixed_overlap: 150

  # 'semantic' 策略的配置
  semantic_target: 1000 # 语义块组合的目标 token 上限
  semantic_overlap: 150   # 语义块之间的目标重叠 token

Embedding:
  api_key: "sk-25073b1d5af2464292d41bfb04d92a7e"
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  model_name: "text-embedding-v4"
  dimensions: 1024
  max_batch_size: 10

LLM:
  api_key: "sk-5d982b3ee78f4a4f90e46d18aab0eb4d"
  base_url: "https://api.deepseek.com"
  model_name: "deepseek-chat"
  max_async: 4

VLM:
  api_key: "sk-25073b1d5af2464292d41bfb04d92a7e"
  base_url: "https://qwen-vl.evanzhong.cn/v1"
  model_name: "Qwen/Qwen2.5-VL-7B-Instruct"
  max_async: 1

Extraction:
  # 用于 Prompt，定义实体可以被分为哪些类型
  entity_types:
    - "person"
    - "organization"
    - "location"
    - "event"
    - "product"
    - "concept"
    - "equipment"
    - "category"
    - "other"
  # 控制是否启用二次修正流程。大于0则启用。
  entity_extract_max_gleaning: 1