General:
  rag_space: "my_electronics_kb" # 你的知识库名称，将作为顶级文件夹名

PDF processing:
  OCR: false
  Page save: false  # 设置为 true 来保存分页图片，false 则不保存
  Page dpi: 200    # 设置保存图片的分辨率 (DPI)

Chunking:
  strategy: semantic  # 分块策略。可选值: 'fixed' 或 'semantic'

  # 'fixed' 策略的配置
  fixed_size: 1000
  fixed_overlap: 150

  # 'semantic' 策略的配置
  semantic_target: 900 # 语义块组合的目标 token 上限
  semantic_overlap: 150   # 语义块之间的目标重叠 token
  semantic_pre_context_limit: 50 # 当一个大单元（如表格）开启新分块时，可额外包含的前置上下文（如标题）的最大token限制
  semantic_hard_limit: 500 # 如果一个单元本身就超过这个值，则完全放弃为下一个块创建重叠

Embedding:
  api_key: "sk-******"
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  model_name: "text-embedding-v4"
  dimensions: 1024
  max_batch_size: 10
  max_retries: 3
  retry_delay_seconds: 2
  
LLM:
  api_key: "sk-******"
  base_url: "https://api.deepseek.com"
  model_name: "deepseek-chat"
  max_async: 4
  max_retries: 3
  retry_delay_seconds: 2

Extraction:
  # 用于 Prompt，定义实体可以被分为哪些类型
  entity_types:
    - "Manufacturer"
    - "Device"
    - "Package"
    - "Basic Information"
    - "Pin Configuration"
    - "Parameters"
    - "Category"
    - "other"
  # 控制是否启用二次修正流程。大于0则启用。

  entity_extract_max_gleaning: 1

